[package]
name = "ksp_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
krpc-client = { git = "https://github.com/kladd/krpc-client" }
glam = "0.24"